name: run-tests

on: [ push, pull_request ]

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: true

      matrix:
        os: [ ubuntu-latest ]
        php: [8.0, 8.1]
        laravel: [ 9.* ]
        dependency-version: [ prefer-stable ]

    name: Testing Laravel v${{ matrix.laravel }} + PHP v${{ matrix.php }} (${{ matrix.os }})

    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none

      - name: Install dependencies
        run: composer install --no-interaction --no-suggest

      - name: Execute tests
        run: vendor/bin/phpunit